set(_CATKIN_CURRENT_PACKAGE "turtlebot_example")
set(turtlebot_example_VERSION "0.0.0")
set(turtlebot_example_MAINTAINER "user <user@todo.todo>")
set(turtlebot_example_PACKAGE_FORMAT "1")
set(turtlebot_example_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(turtlebot_example_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(turtlebot_example_BUILDTOOL_DEPENDS "catkin")
set(turtlebot_example_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot_example_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(turtlebot_example_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(turtlebot_example_TEST_DEPENDS )
set(turtlebot_example_DOC_DEPENDS )
set(turtlebot_example_URL_WEBSITE "")
set(turtlebot_example_URL_BUGTRACKER "")
set(turtlebot_example_URL_REPOSITORY "")
set(turtlebot_example_DEPRECATED "")